program: ./piiw/online_planning_learning_lightning.py
method: bayes
metric:
  name: train/episode_reward
  goal: maximize
parameters:
  train.learning_rate:
    min: 0.00001
    max: 0.001
  plan.softmax_temperature:
    min: 0.0
    max: 0.7
command:
  - python
  - ${program}
  - ${args_no_hyphens}
  - train.max_epochs=5